
package com.guardian.app.ui

import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material3.Card
import androidx.compose.material3.Text
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import com.guardian.app.EducationArticle

@Composable
fun EducationScreen(onBack: () -> Unit) {
    val articles = remember { getSampleArticles() }
    val categories = articles.map { it.category }.distinct()
    var selectedArticle by remember { mutableStateOf<EducationArticle?>(null) }

    if (selectedArticle != null) {
        ArticleDetailScreen(article = selectedArticle!!) {
            selectedArticle = null // Navigate back
        }
    } else {
        Column(modifier = Modifier.padding(8.dp)) {
            Text("Security Education", style = androidx.compose.material3.MaterialTheme.typography.headlineMedium)
            LazyColumn {
                categories.forEach { category ->
                    item {
                        Text(category, style = androidx.compose.material3.MaterialTheme.typography.titleLarge, modifier = Modifier.padding(vertical = 8.dp))
                    }
                    items(articles.filter { it.category == category }) { article ->
                        ArticleCard(article = article) {
                            selectedArticle = article
                        }
                    }
                }
            }
            Button(onClick = onBack) { Text("Back") }
        }
    }
}

@Composable
fun ArticleCard(article: EducationArticle, onClick: (EducationArticle) -> Unit) {
    Card(
        modifier = Modifier
            .fillMaxWidth()
            .padding(vertical = 4.dp)
            .clickable { onClick(article) }
    ) {
        Column(modifier = Modifier.padding(16.dp)) {
            Text(article.title, style = androidx.compose.material3.MaterialTheme.typography.titleMedium)
        }
    }
}

@Composable
fun ArticleDetailScreen(article: EducationArticle, onBack: () -> Unit) {
    Column(modifier = Modifier.padding(16.dp)) {
        Text(article.title, style = androidx.compose.material3.MaterialTheme.typography.headlineMedium)
        Text(article.category, style = androidx.compose.material3.MaterialTheme.typography.labelMedium)
        Spacer(modifier = Modifier.height(16.dp))
        Text(article.content)
        Spacer(modifier = Modifier.height(16.dp))
        Button(onClick = onBack) {
            Text("Back")
        }
    }
}

fun getSampleArticles(): List<EducationArticle> {
    return listOf(
        EducationArticle(
            id = "1",
            title = "What is Spyware?",
            content = "Spyware is malicious software designed to enter your computer device, gather data about you, and forward it to a third party without your consent. It can be installed without your knowledge and can be very difficult to detect.",
            category = "Basics"
        ),
        EducationArticle(
            id = "2",
            title = "Understanding Zero-Click Attacks",
            content = "A zero-click attack is a type of cyberattack where a device is compromised without any interaction from the user. These are some of the most sophisticated and dangerous types of attacks.",
            category = "Basics"
        ),
        EducationArticle(
            id = "3",
            title = "How to Spot a Phishing Attack",
            content = "Phishing attacks often come in the form of emails or messages that try to trick you into revealing personal information, such as passwords or credit card numbers. Be wary of unsolicited messages with a sense of urgency.",
            category = "Prevention"
        ),
        EducationArticle(
            id = "4",
            title = "Using a VPN",
            content = "A Virtual Private Network (VPN) encrypts your internet traffic and masks your IP address, making it more difficult for third parties to track your online activity.",
            category = "Prevention"
        ),
        EducationArticle(
            id = "5",
            title = "The Importance of Two-Factor Authentication (2FA)",
            content = "2FA adds an extra layer of security to your accounts by requiring a second form of verification in addition to your password. This can be a code sent to your phone or generated by an app.",
            category = "Prevention"
        ),
        EducationArticle(
            id = "6",
            title = "What to Do If You Are Targeted",
            content = "If you suspect you have been targeted by spyware, immediately disconnect your device from the internet and seek expert help. Do not attempt to remove the spyware yourself, as this could alert the attackers.",
            category = "Response"
        )
    )
}
