
import SwiftUI

struct EducationView: View {
    @State private var selectedArticle: EducationArticle? = nil
    private let categories = getSampleArticles().map { $0.category }.removingDuplicates()

    var body: some View {
        NavigationView {
            VStack {
                if selectedArticle != nil {
                    ArticleDetailView(article: selectedArticle!) {
                        selectedArticle = nil // Navigate back
                    }
                } else {
                    List {
                        ForEach(categories, id: \.self) { category in
                            Section(header: Text(category)) {
                                ForEach(getSampleArticles().filter { $0.category == category }) { article in
                                    ArticleCard(article: article) {
                                        selectedArticle = article
                                    }
                                }
                            }
                        }
                    }
                    .listStyle(GroupedListStyle())
                }
            }
            .navigationTitle("Security Education")
        }
    }
}

struct ArticleCard: View {
    let article: EducationArticle
    let onClick: (EducationArticle) -> Void

    var body: some View {
        VStack(alignment: .leading) {
            Text(article.title)
                .font(.headline)
        }
        .contentShape(Rectangle())
        .onTapGesture { onClick(article) }
    }
}

struct ArticleDetailView: View {
    let article: EducationArticle
    let onBack: () -> Void

    var body: some View {
        ScrollView {
            VStack(alignment: .leading) {
                Text(article.title)
                    .font(.largeTitle)
                Text(article.category)
                    .font(.subheadline)
                Divider()
                Text(article.content)
                Button("Back") { onBack() }
            }
            .padding()
        }
    }
}

func getSampleArticles() -> [EducationArticle] {
    return [
        EducationArticle(
            title: "What is Spyware?",
            content: "Spyware is malicious software designed to enter your computer device, gather data about you, and forward it to a third party without your consent. It can be installed without your knowledge and can be very difficult to detect.",
            category: "Basics"
        ),
        EducationArticle(
            title: "Understanding Zero-Click Attacks",
            content: "A zero-click attack is a type of cyberattack where a device is compromised without any interaction from the user. These are some of the most sophisticated and dangerous types of attacks.",
            category: "Basics"
        ),
        EducationArticle(
            title: "How to Spot a Phishing Attack",
            content: "Phishing attacks often come in the form of emails or messages that try to trick you into revealing personal information, such as passwords or credit card numbers. Be wary of unsolicited messages with a sense of urgency.",
            category: "Prevention"
        ),
        EducationArticle(
            title: "Using a VPN",
            content: "A Virtual Private Network (VPN) encrypts your internet traffic and masks your IP address, making it more difficult for third parties to track your online activity.",
            category: "Prevention"
        ),
        EducationArticle(
            title: "The Importance of Two-Factor Authentication (2FA)",
            content: "2FA adds an extra layer of security to your accounts by requiring a second form of verification in addition to your password. This can be a code sent to your phone or generated by an app.",
            category: "Prevention"
        ),
        EducationArticle(
            title: "What to Do If You Are Targeted",
            content: "If you suspect you have been targeted by spyware, immediately disconnect your device from the internet and seek expert help. Do not attempt to remove the spyware yourself, as this could alert the attackers.",
            category: "Response"
        )
    ]
}

extension Array where Element: Hashable {
    func removingDuplicates() -> [Element] {
        var addedDict = [Element: Bool]()
        return filter {
            addedDict.updateValue(true, forKey: $0) == nil
        }
    }
}
